### ISSUE TITLE
Update peer dependencies to support React 16

### ISSUE THREAD

**Issue by lyushenko** [MicheleBertoli/react-count-to#16]
I'm getting these warnings during installation, can you please add React 16 to peer dependencies?
```shell
warning "react-count-to@0.8.1" has incorrect peer dependency "react@^15.0.2".
warning "react-count-to@0.8.1" has incorrect peer dependency "react-dom@^15.0.2".
```

**Comment by MicheleBertoli** [comment]
Fixed in [v0.9.0](https://github.com/MicheleBertoli/react-count-to/releases/tag/v0.9.0), thank you very much @lyushenko.
