### ISSUE TITLE
Counting down from 1 to 0 results in -0

### ISSUE THREAD

**Issue by pwolaq** [MicheleBertoli/react-count-to#19]
I just experienced some weird behaviour - when counting down (eg. from 1 to 0) the remaining value after counting completes is -0.

**Comment by MicheleBertoli** [comment]
Hey @pwolaq, thanks for opening this issue.

That might be some rounding issue related to `toFixed`, for example:
```js
-0.1.toFixed()

// -0
```

Do you have capacity to look into this?

**Comment by pwolaq** [comment]
Ok, I have seen it again and I think it is connected with precision in representing the numbers.

It occurred with the following props: 
- from: 4
- to: 0
- delay: 10
- speed: 1500

Given that the current behaviour is to divide the difference (in this example = 4) by speed / delay = 150, it means that every time the counter was decreased by 4 / 150 = 0,02(6) it is very reasonable that precision errors were added up and resulted in final number below 0.

This behaviour should be fixed in #22 because of the different logic behind calculating current counter value.

**Comment by MicheleBertoli** [comment]
Merged #22
