### ISSUE TITLE
Pass state to count-to question

### ISSUE THREAD

**Issue by tachun** [MicheleBertoli/react-count-to#2]
Hello @MicheleBertoli ,

Thanks for your great job, it's awesome! 
I've used it in my previous project and it works fine, but today I'm trying to pass a number (this.state.to) as your demo but it doesn't work, I'm quite new with React, could you give me a hand on it please?

here is my code:

    export class Ranking extends React.Component {

        constructor() {
            super();
            this.companies = [
                {name: 'GOOGLE', cat: 'note'},
                {name: 'YAHOO', cat: 'onlinePresence'},
                {name: 'MICROSOFT', cat: 'ecosysteme'},
                {name: 'APPLE', cat: 'mainTechnologic'}
            ];

            this.catCount = [
                {name: 'note', count: 120},
                {name: 'onlinePresence', count: 235},
                {name: 'ecosysteme', count: 451},
                {name: 'mainTechnologic', count: 78}
            ];

            this.noteSelector = this.noteSelector.bind(this);
            this.state = {to: ''};
        }

        noteSelector(company) {
            let count = _.find(this.catCount,{name:company.cat}).count;
            this.setState({to: count});
        }
        
        render() {
            let companiesList = this.companies.map((company, index) => {
                let currentCount = Number(this.state.to);
                return (
                    <div key={index}>
                        <button className="ranking-list" onClick={this.noteSelector.bind(null, company)}>Load counts</button>
                        <br/>
                        Without counter: {currentCount}
                        <br/>
                        With counter:
                        <CountNumbers to={currentCount} speed={2000} />
                    </div>
                )
            });

            return (
                <div className="ranking-lists">{companiesList}</div>
            );
        }
    }

**Comment by tachun** [comment]
Work like a charm!! thx!

**Comment by MicheleBertoli** [comment]
Thank you very much @tachun.
The component used to work on the first load only, but I changed it to start counting when props change.

Here is your demo:
![count-to](https://cloud.githubusercontent.com/assets/1308971/10261936/0e6ed332-69aa-11e5-9346-d70c4cd4c93f.gif)

**Comment by touqeerkhan11** [comment]
Hi and I'am sorry to resurface this issue but could you please tell me why the counter is restarting when ever a setState is triggered in any parent component ? This is my component hierarchy
--App <-- im setting the state over here 
  --Page
     --Main
        --Counter <-- and counter is restarting
Any help will be much appriciated, thanks.

**Comment by touqeerkhan11** [comment]
I have solved my issue by removing the componentWillReceiveProps(nextProps) function but i was wondering if there is or should be a better way to do it.

**Comment by MicheleBertoli** [comment]
thanks for your comment @touqeerkhan11 
the issue is fixed in [0.5.1](https://github.com/MicheleBertoli/react-count-to/releases/tag/v0.5.1)
